version: '3.8'
services:
  frontend:
    image: antoniopapa1991/admin-frontend
    depends_on:
      - backend
    networks:
      - app

  backend:
    container_name: admin_api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_HOST: db
      DB_DATABASE: admin
      DB_USERNAME: root
      DB_PASSWORD: strongr324!w.LdOOfword
    ports:
      - 8000:8000
    volumes:
      - .:/var/www/app
    depends_on:
      - db
    networks:
      - app

  db:
    container_name: admin_db
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: strongr324!w.LdOOfword
      MYSQL_ROOT_PASSWORD: strongr324!w.LdOOfword
    volumes:
      - .docker/mysql:/etc/mysql/conf.d
      - .docker/mysql/log:/var/log/mysql
      - .docker/mysql/dbdata:/var/lib/mysql
    ports:
      - 33866:3386
    networks:
      - app

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      - PMA_HOST=db
    networks:
      - app
networks:
  app: null
