version: '3.7'
services:
  frontend:
    image: antoniopapa1991/admin-frontend

  backend:

  db:
    container_name: admin_db
    image: mysql:5.7.22
    environment:
      MYSQL_DATABASE: admin
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata: /var/lib/mysql